import os
import json
import logging
from abc import ABC, abstractmethod
from typing import List, Dict, Any, Optional
from app.models.schemas import AIAssessment, VerificationResult, Evidence
from app.core.config import settings

logger = logging.getLogger("unmask.ai_reasoning")

SYSTEM_INSTRUCTION = """UNMASK AI is an evidence-based cybersecurity explanation assistant.

You receive structured security evidence generated by deterministic analysis and verification systems.

Your job is to explain the evidence clearly to a non-technical user.

Do not invent facts.
Do not create verification results.
Do not claim an entity is malicious unless the supplied evidence explicitly supports that conclusion.
Do not override the deterministic risk level.
Do not expose hidden reasoning or chain-of-thought.
Use only the supplied evidence.
Clearly distinguish verified, mismatched, suspicious, and unverified information."""

def build_structured_evidence_payload(
    claimed_org: str,
    phone_numbers: List[str],
    urls: List[str],
    qr_codes: List[str],
    verification: Optional[VerificationResult],
    social_engineering: Dict[str, Any],
    risk_score: int,
    risk_level: str
) -> Dict[str, Any]:
    phone_verification = []
    domain_verification = []
    qr_verification = []

    if verification:
        for p in verification.phones:
            phone_verification.append({
                "number": p.entity,
                "status": p.status,
                "evidence": p.evidence
            })

        for d in verification.domains:
            domain_verification.append({
                "domain": d.entity,
                "status": d.status,
                "evidence": d.evidence
            })

        for q in verification.qr_codes:
            qr_verification.append({
                "destination": q.entity,
                "status": q.status,
                "evidence": q.evidence
            })

    signals = social_engineering.get("detected_phrases", [])
    if not signals:
        if social_engineering.get("has_urgency"):
            signals.append("urgency")
        if social_engineering.get("has_credential_request"):
            signals.append("credential request")
        if social_engineering.get("has_payment_request"):
            signals.append("payment request")

    return {
        "claimed_organization": claimed_org,
        "extracted_phone_numbers": phone_numbers,
        "phone_verification": phone_verification,
        "extracted_urls": urls,
        "domain_verification": domain_verification,
        "qr_verification": qr_verification,
        "social_engineering_signals": signals,
        "risk_level": risk_level,
        "risk_score": risk_score
    }

class AIReasoningProvider(ABC):
    @abstractmethod
    def evaluate(
        self,
        claimed_org: str,
        extracted_text: str,
        phone_numbers: List[str],
        urls: List[str],
        qr_codes: List[str],
        verification: Optional[VerificationResult],
        social_engineering: Dict[str, Any],
        risk_score: int,
        risk_level: str,
        evidence_items: Optional[List[Evidence]] = None
    ) -> AIAssessment:
        pass

class MockReasoningProvider(AIReasoningProvider):
    """
    Deterministic local AI reasoning provider for demo and evaluation.
    Synthesizes observed data + verification results + security signals + deterministic risk score
    into clear explanations without requiring an external API key.
    """
    def evaluate(
        self,
        claimed_org: str,
        extracted_text: str,
        phone_numbers: List[str],
        urls: List[str],
        qr_codes: List[str],
        verification: Optional[VerificationResult],
        social_engineering: Dict[str, Any],
        risk_score: int,
        risk_level: str,
        evidence_items: Optional[List[Evidence]] = None
    ) -> AIAssessment:
        has_phone_mismatch = False
        has_domain_mismatch = False
        has_qr_mismatch = False
        has_verified_phone = False
        has_verified_domain = False
        has_verified_qr = False
        is_org_verified = False

        if verification:
            if verification.organization and verification.organization.status == "verified":
                is_org_verified = True

            for p in verification.phones:
                if p.status == "mismatch":
                    has_phone_mismatch = True
                elif p.status == "verified":
                    has_verified_phone = True

            for d in verification.domains:
                if d.status == "mismatch":
                    has_domain_mismatch = True
                elif d.status == "verified":
                    has_verified_domain = True

            for q in verification.qr_codes:
                if q.status == "mismatch":
                    has_qr_mismatch = True
                elif q.status == "verified":
                    has_verified_qr = True

        has_urgency = social_engineering.get("has_urgency", False)
        has_credential = social_engineering.get("has_credential_request", False)
        has_payment = social_engineering.get("has_payment_request", False)

        # 1. High Risk / Potential Impersonation Case
        if risk_level in ["high", "suspicious"] and (has_phone_mismatch or has_domain_mismatch or has_qr_mismatch or risk_level == "high"):
            headline = "Potential impersonation detected"

            mismatch_types = []
            if has_phone_mismatch:
                mismatch_types.append("phone-number mismatch")
            if has_domain_mismatch:
                mismatch_types.append("domain mismatch")
            if has_qr_mismatch:
                mismatch_types.append("QR destination mismatch")

            if mismatch_types:
                mismatches_str = " and a ".join(mismatch_types)
                summary = f"UNMASK found multiple signals that conflict with the claimed organization, including a {mismatches_str}."
            else:
                summary = "UNMASK identified high-risk signals including coercive framing and unverified communication patterns."

            key_findings = []
            reasoning_basis = []

            if has_phone_mismatch:
                key_findings.append("Phone number does not match the trusted contact associated with the claimed organization.")
                reasoning_basis.append("Phone number does not match the trusted organization contact.")
            
            if has_domain_mismatch:
                key_findings.append("Domain does not match the trusted domain of the claimed organization.")
                reasoning_basis.append("Domain does not match the trusted organization domain.")

            if has_qr_mismatch:
                key_findings.append("QR destination does not match the trusted organization domain.")
                reasoning_basis.append("QR destination does not match the trusted organization domain.")

            if has_urgency:
                key_findings.append("The message uses high-pressure language encouraging immediate action.")
                reasoning_basis.append("Message contains high-pressure language.")

            if has_credential:
                key_findings.append("The message prompts the recipient to verify or confirm account credentials.")
                reasoning_basis.append("Request for sensitive account credential verification.")

            if has_payment:
                key_findings.append("The message requests prompt fund transfer or payment.")
                reasoning_basis.append("Request for direct payment or financial transfer.")

            if not key_findings:
                key_findings.append("High-risk verification signals were flagged during forensic evaluation.")
                reasoning_basis.append("Multiple forensic risk rules triggered.")

            recommended_action = (
                "Do not call the number or scan the QR code provided in the message. "
                "Verify the organization through an independently sourced official channel."
            )
            confidence = "high"

            return AIAssessment(
                headline=headline,
                summary=summary,
                key_findings=key_findings,
                confidence=confidence,
                recommended_action=recommended_action,
                reasoning_basis=reasoning_basis
            )

        # 2. Safe / Low-Risk Case
        elif risk_level == "safe" and (is_org_verified or has_verified_phone or has_verified_domain or has_verified_qr or not (phone_numbers or urls or qr_codes)):
            headline = "Low-risk indicators detected"
            summary = (
                "Low-risk indicators detected. The available contact and domain information are consistent with "
                "the claimed organization. Continue to remain cautious with unexpected requests."
            )
            key_findings = []
            reasoning_basis = []

            if has_verified_phone:
                key_findings.append("Phone number matches official contact reference for the organization.")
                reasoning_basis.append("Phone number matches official contact reference.")

            if has_verified_domain:
                key_findings.append("Domain matches official domain reference for the organization.")
                reasoning_basis.append("Domain matches official domain reference.")

            if has_verified_qr:
                key_findings.append("QR code destination points to official organization domain.")
                reasoning_basis.append("QR destination verified with official domain.")

            if is_org_verified and not key_findings:
                key_findings.append("Claimed organization is recognized in trusted registry.")
                reasoning_basis.append("Organization identity verified in trusted registry.")

            if not key_findings:
                key_findings.append("Available contact and domain information are consistent with the claimed organization.")
                reasoning_basis.append("Verification checks match established reference parameters.")

            if not has_urgency:
                key_findings.append("No high-pressure urgency language was detected.")
                reasoning_basis.append("No pressure or coercive signals found.")

            recommended_action = "Content appears consistent with standard communication. Continue to exercise standard verification practices."
            confidence = "high" if (has_verified_phone or has_verified_domain) else "medium"

            return AIAssessment(
                headline=headline,
                summary=summary,
                key_findings=key_findings,
                confidence=confidence,
                recommended_action=recommended_action,
                reasoning_basis=reasoning_basis
            )

        # 3. Unverified Case (No trusted reference or unknown org)
        else:
            headline = "Organization identity unverified"
            summary = "UNMASK could not independently verify the claimed organization with the available sources."
            
            key_findings = [
                "UNMASK could not independently verify the claimed organization with the available sources.",
                "Contact details and links could not be matched against known official records."
            ]
            reasoning_basis = [
                "No trusted reference record exists in directory for claimed entity.",
                "Independent verification recommended before responding."
            ]

            if has_urgency:
                key_findings.append("The message contains high-pressure urgency language.")
                reasoning_basis.append("Urgency framing detected in unverified message.")

            recommended_action = "Verify the organization through an independently sourced official channel before taking action."
            confidence = "medium"

            return AIAssessment(
                headline=headline,
                summary=summary,
                key_findings=key_findings,
                confidence=confidence,
                recommended_action=recommended_action,
                reasoning_basis=reasoning_basis
            )

class GeminiReasoningProvider(AIReasoningProvider):
    """
    Live AI reasoning provider using Google Gemini API.
    Sends structured evidence to Gemini and returns validated AIAssessment.
    """
    def __init__(self, api_key: str, model_name: str = "gemini-3.8-flash"):
        self.api_key = api_key
        self.model_name = model_name

    def evaluate(
        self,
        claimed_org: str,
        extracted_text: str,
        phone_numbers: List[str],
        urls: List[str],
        qr_codes: List[str],
        verification: Optional[VerificationResult],
        social_engineering: Dict[str, Any],
        risk_score: int,
        risk_level: str,
        evidence_items: Optional[List[Evidence]] = None
    ) -> AIAssessment:
        if not self.api_key:
            raise ValueError("Gemini API key missing")

        payload = build_structured_evidence_payload(
            claimed_org=claimed_org,
            phone_numbers=phone_numbers,
            urls=urls,
            qr_codes=qr_codes,
            verification=verification,
            social_engineering=social_engineering,
            risk_score=risk_score,
            risk_level=risk_level
        )

        user_prompt = (
            "Analyze the following structured evidence and return ONLY a JSON object matching the requested schema:\n"
            f"{json.dumps(payload, indent=2)}"
        )

        models_to_try = [self.model_name]
        for m in ["gemini-3.6-flash", "gemini-3.7-flash", "gemini-3.5-flash"]:
            if m not in models_to_try:
                models_to_try.append(m)

        last_error = None
        for m in models_to_try:
            try:
                from google import genai
                from google.genai import types

                client = genai.Client(api_key=self.api_key)
                response = client.models.generate_content(
                    model=m,
                    contents=user_prompt,
                    config=types.GenerateContentConfig(
                        system_instruction=SYSTEM_INSTRUCTION,
                        response_mime_type="application/json",
                        response_schema=AIAssessment,
                        temperature=0.2
                    )
                )

                if response and response.text:
                    text = response.text.strip()
                    if text.startswith("```"):
                        text = text.split("\n", 1)[-1].rsplit("```", 1)[0].strip()
                    return AIAssessment.model_validate_json(text)
                else:
                    raise ValueError("Empty response text from Gemini API")
            except Exception as e:
                last_error = e
                # If 503 high demand or 404 deprecated model error, try next candidate model
                continue

        err_msg = str(last_error) if last_error else "Gemini API unavailable"
        if self.api_key:
            err_msg = err_msg.replace(self.api_key, "[REDACTED_API_KEY]")
        raise RuntimeError(f"Gemini generation error: {err_msg}")

class FaultyProvider(AIReasoningProvider):
    """
    Provider simulator that raises an Exception (for testing fallback resilience).
    """
    def evaluate(self, *args, **kwargs) -> AIAssessment:
        raise RuntimeError("AI provider connection error")

def get_provider_from_config() -> AIReasoningProvider:
    provider_name = (settings.AI_REASONING_PROVIDER or "mock").lower().strip()
    api_key = settings.GEMINI_API_KEY

    if provider_name == "gemini":
        if api_key:
            return GeminiReasoningProvider(api_key=api_key)
        else:
            logger.info("Gemini unavailable; using local reasoning provider.")
            return MockReasoningProvider()

    return MockReasoningProvider()

class AIReasoningService:
    def __init__(self, provider: Optional[AIReasoningProvider] = None):
        self.provider = provider or get_provider_from_config()

    def generate_assessment(
        self,
        claimed_org: str,
        extracted_text: str,
        phone_numbers: List[str],
        urls: List[str],
        qr_codes: List[str],
        verification: Optional[VerificationResult],
        social_engineering: Dict[str, Any],
        risk_score: int,
        risk_level: str,
        evidence_items: Optional[List[Evidence]] = None
    ) -> AIAssessment:
        try:
            return self.provider.evaluate(
                claimed_org=claimed_org,
                extracted_text=extracted_text,
                phone_numbers=phone_numbers,
                urls=urls,
                qr_codes=qr_codes,
                verification=verification,
                social_engineering=social_engineering,
                risk_score=risk_score,
                risk_level=risk_level,
                evidence_items=evidence_items
            )
        except Exception as e:
            err_msg = str(e)
            if self.provider and getattr(self.provider, "api_key", None):
                err_msg = err_msg.replace(self.provider.api_key, "[REDACTED_API_KEY]")
            logger.info(f"Gemini unavailable; using local reasoning provider. Details: {err_msg}")
            fallback_provider = MockReasoningProvider()
            return fallback_provider.evaluate(
                claimed_org=claimed_org,
                extracted_text=extracted_text,
                phone_numbers=phone_numbers,
                urls=urls,
                qr_codes=qr_codes,
                verification=verification,
                social_engineering=social_engineering,
                risk_score=risk_score,
                risk_level=risk_level,
                evidence_items=evidence_items
            )
